import Table from "../components/Table";

export default function Usuario() {
  const sampleData = [
    { id: 1, name: "John Doe", email: "john.doe@example.com" },
    { id: 2, name: "Jane Smith", email: "jane.smith@example.com" },
    { id: 3, name: "Alice Johnson", email: "alice.johnson@example.com" },
    { id: 4, name: "Michael Brown", email: "michael.brown@example.com" },
    { id: 5, name: "Sarah Clark", email: "sarah.clark@example.com" },
    { id: 6, name: "Christopher Lee", email: "christopher.lee@example.com" },
    { id: 7, name: "Laura Martinez", email: "laura.martinez@example.com" },
    { id: 8, name: "Daniel Garcia", email: "daniel.garcia@example.com" },
    { id: 9, name: "Jennifer Nguyen", email: "jennifer.nguyen@example.com" },
    { id: 10, name: "Brian Rodriguez", email: "brian.rodriguez@example.com" },
    { id: 11, name: "Megan Hernandez", email: "megan.hernandez@example.com" },
    { id: 12, name: "Matthew Wilson", email: "matthew.wilson@example.com" },
    { id: 13, name: "Amy Wright", email: "amy.wright@example.com" },
    { id: 14, name: "Kevin Taylor", email: "kevin.taylor@example.com" },
    { id: 15, name: "Emma King", email: "emma.king@example.com" },
    { id: 16, name: "Ryan Lewis", email: "ryan.lewis@example.com" },
    { id: 17, name: "Angela Scott", email: "angela.scott@example.com" },
    { id: 18, name: "Jonathan Perez", email: "jonathan.perez@example.com" },
    { id: 19, name: "Nicole Baker", email: "nicole.baker@example.com" },
    { id: 20, name: "Justin Edwards", email: "justin.edwards@example.com" },
    { id: 21, name: "Stephanie Hill", email: "stephanie.hill@example.com" },
    { id: 22, name: "Nathan Rivera", email: "nathan.rivera@example.com" },
    { id: 23, name: "Kimberly Cooper", email: "kimberly.cooper@example.com" },
    { id: 24, name: "Patrick Long", email: "patrick.long@example.com" },
    { id: 25, name: "Christina Morris", email: "christina.morris@example.com" },
    { id: 26, name: "Brandon Cook", email: "brandon.cook@example.com" },
    { id: 27, name: "Melissa Reed", email: "melissa.reed@example.com" },
    { id: 28, name: "Timothy Brooks", email: "timothy.brooks@example.com" },
    { id: 29, name: "Amanda Bennett", email: "amanda.bennett@example.com" },
    { id: 30, name: "Jeremy Gray", email: "jeremy.gray@example.com" },
    { id: 31, name: "Laura Mitchell", email: "laura.mitchell@example.com" },
    { id: 32, name: "Alexander Wright", email: "alexander.wright@example.com" },
    { id: 33, name: "Samantha Walker", email: "samantha.walker@example.com" },
    { id: 34, name: "Dennis Nelson", email: "dennis.nelson@example.com" },
    { id: 35, name: "Jessica Baker", email: "jessica.baker@example.com" },
    { id: 36, name: "Diana Martinez", email: "diana.martinez@example.com" },
    { id: 37, name: "Russell Hall", email: "russell.hall@example.com" },
    { id: 38, name: "Kathleen Bell", email: "kathleen.bell@example.com" },
    { id: 39, name: "Shawn Powell", email: "shawn.powell@example.com" },
    { id: 40, name: "Tiffany Allen", email: "tiffany.allen@example.com" },
    { id: 41, name: "Alan Gonzalez", email: "alan.gonzalez@example.com" },
  ];

  return <Table data={sampleData} link={"/registrar-usuario"} />;
}
